# Generated by hand for TanPit decimal gate

from django.db import migrations, models


def create_decimal_gate(apps, schema_editor):
    GateSwitch = apps.get_model("pits", "GateSwitch")
    GateSwitch.objects.get_or_create(
        key="ph_one_decimal",
        defaults={"label": "酸碱度必须一位小数", "enabled": False},
    )


class Migration(migrations.Migration):
    dependencies = [("pits", "0001_initial")]
    operations = [
        migrations.CreateModel(
            name="GateSwitch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("key", models.CharField(max_length=40, unique=True)),
                ("label", models.CharField(max_length=120)),
                ("enabled", models.BooleanField(default=False)),
            ],
        ),
        migrations.RunPython(create_decimal_gate, migrations.RunPython.noop),
    ]
